lib/stm32/f0/rcc.c

Really use RCC_CFGR_PLLMUL negated as a mask.
Signed-off-by: Daniel Serpell <daniel.serpell@gmail.com>

stm32: f0: Fixes setting of PLL multiplication factor

---

lib/stm32/desig.c

When converting the uniqute id to a hex string, it seems more sensible to put the higher nibble in the string before the lower nibble.

[stm32] desig: high nibble to hex char first

---

include/libopencm3/stm32/f0/tsc.h

TSC_IOGxCR is actually a 32 bit register, of which 13 bits are used
(rest are reserved).
Also, added x-1 since G0 is not a valid group, TSC_IOGCSR_GxE(1) is supposed
to be at 0x34, not 0x38.

stm32f0: Fix TSC_IOGxCR

---

Makefile
README.md

This has hurt many many many people over it's lifetime, by confusing their
multilib toolchains.  Simply drop it outright.  People who _really_ know what
they're doing are still perfectly entitled to "install" portions of this
project in suitable locations for their own use.

Drop "install" target and documentation.

---

include/libopencm3/cm3/cortex.h

In particular, PRIMASK and FAULTMASK operations could be optimized out by gcc.
This is not a complete fix for issue #475 , in fact it only addresses a problem exposed by 475.
This adds the "volatile" keyword to all the inline assembly in cm3.h.
gcc docs say "You can prevent an asm instruction from being deleted by writing the keyword volatile after the asm.". Testing (see comments of github issue #475 ) shows that indeed gcc can remove some inline asm, in at least this situation:
-multiple calls to cm_is_masked_interrupts() in the same scope/context
- -Os or -O2 optimization
This is a problem because the value of PRIMASK could change between two calls to cm_is_masked_interrupts().
Adding the volatile keyword fixes this, and probably costs less than adding a full barrier (like adding …

Cortex-M defines : fix potential issue with optimized-out inline __asm__

---

lib/stm32/f7/Makefile

The Makefile for the stm32f7 library still used CFLAGS instead of TGT_CFLAGS, leading to a build failure when passing CFLAGS as a make option.

stm32f7: fix build failure when CFLAGS is set

---

lib/stm32/f4/rcc.c

Fixes: 57c2b00a69f97205313e1c7ab8116ee1893b231e
There was an issue with the pllp value calculation where the masking was done
in the wrong place. The pllp value was always equivalent to 2 (the bits were
always set to 0b00) which could result in an undesired system clock frequency.

stm32f4: rcc: fix setup of main system clock with pllp

---

include/libopencm3/cm3/fpb.h

The check to see if the architecture is ARMv7 was negated incorrectly, reporting an error if either of `__ARM_ARCH_7M__` or `__ARM_ARCH_7EM__` is not defined instead of only triggering when both are undefined.
AFAICT,  `-mcpu=cortex-m3` only defines `__ARM_ARCH_7M__` and `-mcpu=cortex-m4` only defines `__ARM_ARCH_7EM__`, so this always errors out.
This commit makes the check consistent with the versions in `itm.h` and `tpiu.h`.

cm3/fpb: Fix overly strict ARMv7 check

---

include/libopencm3/stm32/can.h

According to several reference manuals for MCUs of the STM32F4 series, the CAN_FMR_CAN2SB_SHIFT value should be 8, not 15.

stm32: can: Fixed incorrect CAN_FMR_CAN2SB_SHIFT value

---

include/libopencm3/stm32/l0/irq.json

tim3 interrupt is wired to nvic channel 16 if present. add it to irq.json definition.

stm32l0: NVIC: channel 16 is tim3 on stm32l0x0, stm32l0x1 and stm32l0x2.

---

lib/stm32/l0/rcc.c

I discovered this bug when trying to use HSE as PLL source on the STM32L0. In the function rcc_clock_setup_pll() in l0/rcc.c, when the PLL source is not set correctly, it will get stuck in an endless loop waiting for the PLLON flag.

Set PLL source in rcc_clock_setup_pll() for STM32L0

---

lib/stm32/f2/rcc.c
lib/stm32/f4/rcc.c
lib/stm32/f7/rcc.c
lib/stm32/l1/rcc.c

This bug was found and fixed by a coworker. The clock configuration function for the STM32F427 failed to reconfigure the PLL correctly, because it did not disable the PLL before changing its configuration.
This has only been tested on the STM32F427. I ported the fix to the F2 and the F7 as they seem to share the same logic, but I admit that I haven't tested on those.

stm32: pll: disable before configuring

---

lib/stm32/f0/adc.c

Save me from directly manipulating registers in my code.

stm32f0: adc: API call to clear EOS flag

---

include/libopencm3/stm32/common/exti_common_all.h
include/libopencm3/stm32/common/exti_common_v1.h
include/libopencm3/stm32/f1/exti.h
include/libopencm3/stm32/f2/exti.h
include/libopencm3/stm32/f3/exti.h
include/libopencm3/stm32/f4/exti.h
include/libopencm3/stm32/l0/exti.h
include/libopencm3/stm32/l1/exti.h
include/libopencm3/stm32/l4/exti.h

Preparation for stm32g0 support, as this chip's exti register map evolved and is no longer common.. G0 exti header will redefine these, but will use regular code with minimal modifications.

stm32: exti: move register definition of all current stm32 devices to common_v1

---

lib/stm32/f1/adc.c

Doc fix: Code wouldn't compile. I've updated two deprecated functions and fixed a define that didn't exist.

stm32f1: adc: fixed deprecated/broken example code

---

include/libopencm3/stm32/crc.h
include/libopencm3/stm32/g0/crc.h
include/libopencm3/stm32/g0/exti.h
include/libopencm3/stm32/g0/i2c.h
include/libopencm3/stm32/g0/iwdg.h
include/libopencm3/stm32/g0/rng.h
include/libopencm3/stm32/g0/spi.h
include/libopencm3/stm32/g0/timer.h
include/libopencm3/stm32/g0/usart.h
include/libopencm3/stm32/i2c.h
include/libopencm3/stm32/iwdg.h
include/libopencm3/stm32/spi.h
include/libopencm3/stm32/timer.h
include/libopencm3/stm32/usart.h
lib/stm32/g0/Makefile
lib/stm32/g0/exti.c

Hi,
Here's some more g0 support, making it a bit more usefull - adding iwdg/usart/spi/i2c/rng/crc and timer.
Not much new stuff here, a couple of new regs and bits for Timer and RNG but that's all.
I need to review adc and dma/dmamux stuff, but that will wait the next patchset

stm32g0: support++

---

include/libopencm3/stm32/common/dmamux_common_all.h
include/libopencm3/stm32/dma.h
include/libopencm3/stm32/dmamux.h
include/libopencm3/stm32/g0/dma.h
include/libopencm3/stm32/g0/dmamux.h
lib/stm32/common/dmamux.c
lib/stm32/g0/Makefile

hi,
Here's a PR to enable dma on stm32g0 and add dmamux, a new peripheral needed to handle dma request peripheral mapping, found on a couple of new st chips.

stm32g0 add dma & dmamux

---

include/libopencm3/stm32/l4/usart.h

UART4 and UART5 are mistakenly defined to USART4 and USART5 where it should be UART4 and UART5.

stm32l4: Fix typo impacting uart4 and uart5

---

include/libopencm3/stm32/g0/spi.h
lib/stm32/g0/Makefile

Seems like the STM32G0 family uses the new SPI version.

stm32g0: use spi v2

---

Makefile

It's very difficult to write makefiles which can cope with dirnames or filenames containing whitespaces, especially if you want it to work across different versions of make. For this reason, absolute paths should be avoided if possible, relative paths are much safer.
In this case, the definition of SRCLIBDIR in the top level Makefile causes problems with GNU make v4.3 and later. However, this definition is redundant, as all submakefiles have sensible defaults (either .. or ../..). These defaults will work even if the current dir name contains spaces.

Remove SRCLIBDIR definition from the top Makefile

---

include/libopencm3/stm32/f3/adc.h
lib/stm32/f3/adc.c

Missing defines for ADC_CCR DUAL values have also been added.

stm32f3: fix missing reg mask for adc_set_multi_mode

---

include/libopencm3/stm32/f2/memorymap.h
include/libopencm3/stm32/f3/memorymap.h
include/libopencm3/stm32/f4/memorymap.h
include/libopencm3/stm32/f7/memorymap.h
include/libopencm3/stm32/g0/memorymap.h
include/libopencm3/stm32/g4/memorymap.h
include/libopencm3/stm32/h7/memorymap.h
include/libopencm3/stm32/l0/memorymap.h
include/libopencm3/stm32/l1/memorymap.h
include/libopencm3/stm32/l4/memorymap.h

FLASH_BASE was already defined for some and PERIPH_BASE for all but one,
but this makes these available for all families. Note that the value is
identical for all familes (I doublechecked the more exotic ones such
STM32H7), but it is still useful to have these defines to make code more
readable and so that libopencm3 users can write portable code without
having to check that these are identical on all STM32 families.
This fixes https://github.com/libopencm3/libopencm3-examples/issues/224 (which I accidentally reported in the wrong repository).

stm32: Define FLASH_BASE and PERIPH_BASE for all families

---

Makefile
README.md

See https://github.com/libopencm3/libopencm3/pull/1287
- split white space change in another commit,
- remove list of targets from README to avoid duplicated work and add a list-targets in Makefile,
- replace “footprint of the library” by “build time”, as someone could wrongly understand that the compiled size of the lib depends on the list of built targets.

README: added info about partial build, take 2

---

include/libopencm3/stm32/common/usart_common_v2.h

Just a small change to fix a wrong character

stm32: fix typo for auto baud rate request bit in USART_RQR

---

doc/Makefile

Add NRF51 and NRF52 into list of targets Doxygen docs are generated for.
Fixes missing documentation.

NRF5x: Enable generation of Doxygen docs

---

ld/devices.data

Add support to generate ld script for nrf51822 devices. In this pull request 3 devices are added: nrf51822aa,nrf51822ab and nrf51822ac. Rom and ram supported by those devices are listed [here](https://infocenter.nordicsemi.com/pdf/nRF51822_PS_v3.4.pdf)  P.76 section 10.6 table 75 . 
Thanks

Add nrf51822 device in devices.data

---

include/libopencm3/stm32/crc.h
include/libopencm3/stm32/g4/crc.h
include/libopencm3/stm32/g4/syscfg.h
include/libopencm3/stm32/g4/usart.h
include/libopencm3/stm32/syscfg.h
include/libopencm3/stm32/usart.h
lib/stm32/g4/Makefile

CRC and USART are just copied from F3, as they should be fully compatible according to this [application note](https://www.st.com/content/ccc/resource/technical/document/application_note/group1/87/f0/7b/96/37/cf/49/b8/DM00442720/files/DM00442720.pdf/jcr:content/translations/en.DM00442720.pdf). LPUART support is not implemented.
I've tested this PR by running [BMP](https://github.com/blackmagic-debug/blackmagic) code on STM32G431 and USART bridge works.

stm32: Support CRC, SYSCFG and USART on G4

---

include/libopencm3/lm4f/uart.h
include/libopencm3/stm32/common/usart_common_all.h
include/libopencm3/usb/cdc.h
lib/lm4f/uart.c
lib/stm32/common/usart_common_all.c

As part of addressing some defects in BMP, we found that the USB CDC support in locm3 didn't support the class specific request `GET_LINE_CODING`.
This PR addresses that by adding the missing define and then providing support for STM32 and LM4F (TM4C) for retrieving the current UART configuration to answer this USB request.

Feature: u(s)art configuration retrieval

---

lib/stm32/l0/rcc.c

The function `rcc_set_lpuart1_sel()` was incorrectly using `RCC_CCIPR_LPTIM1SEL_SHIFT` instead of `RCC_CCIPR_LPUART1SEL_SHIFT`, causing incorrect LPUART1 clock source selection.
This patch corrects the bit shift to ensure the LPUART1SEL field is properly updated.
To verify check [RM0377 Reference manual section 7.3.19](https://www.st.com/resource/en/reference_manual/rm0377-ultralowpower-stm32l0x1-advanced-armbased-32bit-mcus-stmicroelectronics.pdf).

stm32l0: rcc: fix incorrect bit shift in rcc_set_lpuart1_sel()

---

include/libopencm3/stm32/common/timer_common_all.h
lib/stm32/common/timer_common_all.c

When implementing a new feature in Black Magic Debug to soft-start the target power output, we wound up having too interact with the timers and set up the output compare block mode for a channel. This pulls in an extra ~400 bytes of code due to the complex unoptimisable nature of the switch-case-in-switch-case setup of the STM32 `timer_set_oc_mode()` function.
This PR addresses some of this by splitting out the case logic of the outer switch-case into per-channel functions (still exposed by this unified mode set function), saving around 332 bytes when only a single channel is used. It otherwise maintains the exact same logic and call structure for existing code.

Feature: individual STM32 timer oc mode calls

---

lib/cm3/vector.c
lib/cortex-m-generic.ld
lib/stm32/common/st_usbfs_core.c
lib/stm32/st_usbfs_v2.c
lib/usb/usb_dwc_common.c
lib/usb/usb_lm4f.c

This PR aims to improve standards conformance and LTO compatibility.
ISO C forbids casting function pointers to or from `void *` as the size of a function pointer is allowed to be different from the size of a data pointer, the library should never have been doing this and especially as the casts aren't even required, so we eliminate them for all devices BMD compiles for.
It is an error to do pointer arithmetic on a void pointer - `sizeof(void)` has no standards-set size, and the operation is meaningless. Luckily all instances of this are trivially convertible to using properly typed pointers.
LTO requires we mark the vector table, reset vector and vector table's section all used/keep so it doesn't eliminate them due to nothing it can see calling into them.

Fix: Forbidden casts and LTO compatability improvements

---

lib/stm32/common/iwdg_common_all.c

With code that uses IWDG and these operations:
- user code initializes iwdg
- user code jumps to USB-DFU
- USB host triggers a USB exit (e.g. after reflashing, or even just a `dfu-util -R -s 0x8000000:leave ....` command)
- user code will hang in `iwdg_prescaler_busy()` called from `iwdg_set_period_ms()`
F070 Datasheet excerpts : 
```
/* (1) Activate IWDG (not needed if done in option bytes) */
/* (2) Enable write access to IWDG registers */
/* (3) Set prescaler by 8 */
/* (4) Set reload value to have a rollover each 100ms */
/* (5) Check if flags are reset */
/* (6) Refresh counter */
IWDG->KR = IWDG_START; /* (1) */
IWDG->KR = IWDG_WRITE_ACCESS; /* (2) */
IWDG->PR = IWDG_PR_PR_0; /* (3) */
IWDG->RLR = IWDG_RELOAD; /* (4) */
while (IWDG->SR) /* (5) */
{
/* add time out here for a robust …
```

iwdg: START and UNLOCK values before polling Busy

---

.gitignore
cross-files/arm-none-eabi.ini
include/libopencm3/lm3s/meson.build
include/libopencm3/stm32/f0/meson.build
include/libopencm3/stm32/f1/meson.build
include/libopencm3/stm32/f3/meson.build
include/libopencm3/stm32/f4/meson.build
include/libopencm3/stm32/f7/meson.build
include/libopencm3/stm32/h7/meson.build
include/libopencm3/stm32/l4/meson.build
include/meson.build
lib/cm3/meson.build
lib/ethernet/meson.build
lib/lm4f/meson.build
lib/meson.build
lib/stm32/common/meson.build
lib/stm32/f0/meson.build
lib/stm32/f1/meson.build
lib/stm32/f3/meson.build
lib/stm32/f4/meson.build
lib/stm32/f7/meson.build
lib/stm32/h7/meson.build
lib/stm32/l4/meson.build
lib/stm32/meson.build
lib/usb/meson.build
meson.build
meson_options.txt
scripts/irq2nvic_h

In this PR we add support for using the project with the Meson build system. While not a 100% complete port of the Makefile build system, this provides support for all the platforms BMD uses and a few extra we've had people like @northernpaws contribute to the fork project.
This is all tested working on the upstream project and should in theory simplify the CI rebuild process due to how Meson cross files work and operate.
Importantly, this does **not** replace the existing Makefile build system but is instead implemented in tandem with it to provide options for consumers of the project.

Feature: Meson build support

---

include/libopencm3/cm3/scb.h
include/libopencm3/stm32/l4/pwr.h
lib/cm3/scb.c
lib/stm32/l4/pwr.c

Added the following 7 functions which can be used to enter all of the power modes available on the L4. 
- `scb_set_deepsleep(void)`
- sets the deepsleep bit in the m3 registers. This bit controls whether or not the cpu enter sleep mode or one of the deeper sleeps
- `scb_clear_deepsleep(void)`
- clears the deepsleep bit
- `scb_set_sleeponexit(void)`
- sets the sleeponexit bit in the appropriate register. Setting this bit will make the cpu enter into a low power mode when exiting an interrupt
- `scb_clear_sleeponexit(void)`
- clears the sleeponexit bit
- `pwr_set_low_power_run(void)`
- sets the low-power run bit. This bit controls whether the L4 will enters into low-power run or low-power sleep
- `pwr_clear_low_power_run(void)`
- clears the low-power run bit
- …

Adds functions to enter all of the L4 power modes

---

include/libopencm3/stm32/exti.h
include/libopencm3/stm32/g4/exti.h
lib/stm32/g4/Makefile

The STM32G4xx series contain two regular EXTI v1 blocks; one at offset 0x00, the other at offset 0x20.
Add support for EXTI.
This pull request partly overlaps with pull request #1250.

stm32g4: Add EXTI support
